server.port: ${PORT}

cryptoKoshBot:
  baseUrl: ${BOT_BASE_URL}
  updateUrl: event/update
  fallUrl: event/fall
  errorUrl: event/error

coinMarketCap.api:
  url: https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=
  headerKey: X-CMC_PRO_API_KEY
  key: ${API_KEY}